app:
  environment: development
  logLevel: DEBUG

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 192Mi

revisionHistoryLimit: 3

observability:
  traces:
    sampleRatio: 1.0
  collector:
    replicaCount: 1
    podDisruptionBudget:
      enabled: false

