app:
  environment: qa
  logLevel: INFO

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

podDisruptionBudget:
  enabled: true
  minAvailable: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

observability:
  traces:
    sampleRatio: 0.5
  collector:
    replicaCount: 1
    podDisruptionBudget:
      enabled: true

progressiveDelivery:
  enabled: true
  minReadySeconds: 15

resilience:
  minReadySeconds: 15
