apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
  labels:
    app.kubernetes.io/name: observability
    app.kubernetes.io/part-of: enterprise-aks-gitops-platform
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Platform-admin project for the Prometheus Operator and Grafana stack
  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
    - https://github.com/harshilamin/enterprise-aks-gitops-platform.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: monitoring
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
