apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-api.fullname" . }}
  labels:
    {{- include "sample-api.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.app.name | quote }}
  APP_VERSION: {{ .Chart.AppVersion | quote }}
  APP_ENVIRONMENT: {{ .Values.app.environment | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  OTEL_ENABLED: {{ .Values.observability.enabled | quote }}
  OTEL_SERVICE_NAME: {{ .Values.observability.serviceName | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ default (printf "http://%s-otel-collector:%d" (include "sample-api.fullname" .) (int .Values.observability.collector.ports.otlpHttp)) .Values.observability.otlp.endpoint | quote }}
  OTEL_METRIC_EXPORT_INTERVAL_MS: {{ .Values.observability.otlp.metricExportIntervalMs | quote }}
  OTEL_TRACE_SAMPLE_RATIO: {{ .Values.observability.traces.sampleRatio | quote }}
