{{- if .Values.azureKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sample-api.fullname" . }}-azure-key-vault
  labels:
    {{- include "sample-api.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ required "workloadIdentity.clientId is required when Azure Key Vault is enabled" .Values.workloadIdentity.clientId | quote }}
    keyvaultName: {{ required "azureKeyVault.name is required when Azure Key Vault is enabled" .Values.azureKeyVault.name | quote }}
    cloudName: {{ .Values.azureKeyVault.cloudName | quote }}
    tenantId: {{ required "workloadIdentity.tenantId is required when Azure Key Vault is enabled" .Values.workloadIdentity.tenantId | quote }}
    objects: |
{{ include "sample-api.keyVaultObjects" . | indent 6 }}
{{- end }}
